name: Update my blog repository
on: [push]
permissions: write-all
jobs:
  Update-Blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          path: main

      # Build the project in React
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          cd main
          npm ci
          npm run build --if-present

      - name: Clone my personal blog
        uses: actions/checkout@v3
        with:
          repository: juanbeleno/juanbeleno.github.com
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          path: blog

      - name: Update the folder of the social dance project
        run: cp -fR ./main/build ./blog/socialdanceproject

      - name: Commit files
        run: |
          cd blog
          git config --local user.email "jsbeleno@gmail.com"
          git config --local user.name "juanbeleno"
          git remote add origin https://juanbeleno:${{ secrets.GITHUB_TOKEN }}@github.com/juanbeleno/juanbeleno.github.com.git
          git fetch
          git rebase
          git add .
          git commit -m "Automatic update of the social dance project"
          git push
